language: go

go:
  - tip

go_import_path: git.fractalqb.de/fractalqb/xsx

install:
  - go get -u -t

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
