// Code generated by "stringer -type Brace"; DO NOT EDIT.

package gem

import "strconv"

const (
	_Brace_name_0 = "UndefParenSquare"
	_Brace_name_1 = "Curly"
)

var (
	_Brace_index_0 = [...]uint8{0, 5, 10, 16}
)

func (i Brace) String() string {
	switch {
	case 0 <= i && i <= 2:
		return _Brace_name_0[_Brace_index_0[i]:_Brace_index_0[i+1]]
	case i == 4:
		return _Brace_name_1
	default:
		return "Brace(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
